name: Build and test asset

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: [ '*' ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            node_src: https://nodejs.org/dist/v22.15.1/node-v22.15.1.tar.gz
            node_make: VARIATION="glibc-217"
    env:
      NODEJS_VERSION: ${{ matrix.version }}
      NODE_SRC: ${{ matrix.node_src }}
      NODE_MAKE: ${{ matrix.node_make }}
      NEXE_ASSET: ${{ github.workspace }}/nexe-asset
      NEXE_TMP_CACHE_PATH: ${{ github.workspace }}/nexe-tmp
      NEXE_TMP: ${{ github.workspace }}/nexe-tmp/standard
      CCACHE_COMPRESS: '1'
      ErrorView: NormalView
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '23.7'
      - name: Record Node version
        run: |
          echo "NODEJS_VERSION=$(node -p process.versions.node)" >> $env:GITHUB_ENV
          echo "NODEJS_VERSION=$(node -p process.versions.node)" >> "${GITHUB_ENV}"
      - run: npm ci --include dev
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - if: ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm' }}
        run: choco install nasm
      - if: ${{ matrix.os == 'ubuntu-24.04-arm' || matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update
      - if: ${{ matrix.os != 'windows-latest' && matrix.os != 'windows-11-arm' }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.version }}
      - if: ${{ matrix.os == 'windows-latest' || matrix.os == 'windows-11-arm' }}
        run: |
          echo "NEXE_ASSET=${{ env.NEXE_ASSET }}.exe" >> $env:GITHUB_ENV
          echo "EXECUTABLE_SUFFIX=.exe" >> $env:GITHUB_ENV
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: musl static build
        run: |
          nexe_target="$(node -p 'require("./lib/target").getTarget({ platform: "static" }).toString()')"
          echo "NEXE_TARGET=${nexe_target}" >> "${GITHUB_ENV}"
          artefact_name="nexe-asset-${nexe_target}"
          export NEXE_ASSET="${artefact_name}"
          echo "NEXE_ASSET=${NEXE_ASSET}" >> "${GITHUB_ENV}"
          export MUSL_BUILD=yes NEXE_TMP=${{ env.NEXE_TMP_CACHE_PATH }}/musl
          eval $(npx -p node-musl musl-exports)
          export CC="ccache ${CC}" CXX="ccache ${CXX}" LD="ccache ${LD}"
          node tasks/asset-build
          node tasks/asset-test-build
      - if: ${{ matrix.os != 'ubuntu-latest' }}
        name: Build and test asset
        run: node tasks/asset-build && node tasks/asset-test-build
      - name: Update release artefact name
        shell: bash
        run: |
          nexe_target="$(node -p 'require("./lib/target").getTarget().toString()')"
          echo "NEXE_TARGET=${nexe_target}" >> "${GITHUB_ENV}"
          artefact_name="nexe-asset-${nexe_target}${EXECUTABLE_SUFFIX}"
          mv "${NEXE_ASSET}" "${artefact_name}"
          echo "NEXE_ASSET=${artefact_name}" >> "${GITHUB_ENV}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NEXE_ASSET }}
          path: ${{ env.NEXE_ASSET }}
          if-no-files-found: error
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-${{ env.NEXE_TARGET }}${{ env.EXECUTABLE_SUFFIX }}
          path: integration-tests${{ env.EXECUTABLE_SUFFIX }}
          if-no-files-found: error
      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          fail_on_unmatched_files: true
          prerelease: true
          files: ${{ env.NEXE_ASSET }}
